### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by poteto** [poteto/ember-hypersearch#13]
- [ ] Option to persist cache to IndexedDB/WebSQL/localStorage/whatever
- [ ] Fuzzy search in cache
- [ ] Cache selected results
- [ ] Option to restore last selected result on initial render
- [ ] API to remove a single or all cached selected results
- [ ] Cache invalidation after a set amount of time/days

**Comment by davidgoli** [comment]
Any plans to support Ember Data integration? I'd be using this to filter an existing query so that would be super useful
